package adf.sample.model.vo.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 05 12:04:14 CEST 2010
// ---------------------------------------------------------------------
public interface EmployeesView extends ViewObject {
    void setHireDateRangeEnd(Date value);

    void setHireDateRangeStart(Date value);
}
