package adf.sample.model.vo;

import adf.sample.model.vo.common.EmployeesView;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 05 12:03:48 CEST 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesViewImpl extends ViewObjectImpl implements EmployeesView {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesViewImpl() {
    }

    /**
     * Returns the variable value for HireDateRangeStart.
     * @return variable value for HireDateRangeStart
     */
    public Date getHireDateRangeStart() {
        return (Date)ensureVariableManager().getVariableValue("HireDateRangeStart");
    }

    /**
     * Sets <code>value</code> for variable HireDateRangeStart.
     * @param value value to bind as HireDateRangeStart
     */
    public void setHireDateRangeStart(Date value) {
        ensureVariableManager().setVariableValue("HireDateRangeStart", value);
    }

    /**
     * Returns the variable value for HireDateRangeEnd.
     * @return variable value for HireDateRangeEnd
     */
    public Date getHireDateRangeEnd() {
        return (Date)ensureVariableManager().getVariableValue("HireDateRangeEnd");
    }

    /**
     * Sets <code>value</code> for variable HireDateRangeEnd.
     * @param value value to bind as HireDateRangeEnd
     */
    public void setHireDateRangeEnd(Date value) {
        ensureVariableManager().setVariableValue("HireDateRangeEnd", value);
    }
}
