package adf.sample.model.vo.client;

import adf.sample.model.vo.common.EmployeesView;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 05 12:04:14 CEST 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesViewClient extends ViewUsageImpl implements EmployeesView {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesViewClient() {
    }


    public void setHireDateRangeEnd(Date value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setHireDateRangeEnd",new String [] {"oracle.jbo.domain.Date"},new Object[] {value});
        return;
    }

    public void setHireDateRangeStart(Date value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setHireDateRangeStart",new String [] {"oracle.jbo.domain.Date"},new Object[] {value});
        return;
    }
}
